#!/bin/bash

# All the videos 
for i in 1 2 3 4 5 6 7 8 9 10
do
python tools/image_type_change.py \
  --RGB_dir /media/hemin/Data/Video_Test_Set/ASU_VIDEO10/$i \
  --GT_dir /media/hemin/Data/Video_Test_Set/ASU_VIDEO10_GT/$i \
  --output_filetype .png \
  --output_dir /media/hemin/Data/Video_Test_Set/RGB_Version/$i
done
