#!/bin/bash

# All the videos 
num_frames="324 910 519 501 1106 339 418 259 616 410"
num_frames=( $num_frames )
j=0
for i in 1 #2 3 4 5 6 7 8 9 10 
do
python tools/selecting_frames.py \
  --RGB_dir /media/hemin/Data/Video_Test_Set/RGB_Version/$i/Original \
  --GT_dir /media/hemin/Data/Video_Test_Set/RGB_Version/$i/GT/ \
  --output_filetype .png \
  --num_frames ${num_frames[j]} \
  --output_dir /home/hemin/Desktop/Annoataion_Work/Each_Video/Video_$i
let j=$j+1
done 

