#!/bin/bash

# Train the parent for 25 epoch or to your desired epoch first 
epoch=25

python pix2pix_mine2.py \
  --mode train \
  --output_dir /home/hemin/Desktop/Semi_Automatic_OSVOS/Video_1/per20_correct_aug/Trained_Model/$epoch \
  --max_epochs $i \
  --input_dir /home/hemin/Desktop/Semi_Automatic_OSVOS/Video_1/per20_correct_aug/Training_Set/Combine


# take more epochs one after another, starting from the previous epoch 
epoch="25 50 100 200" 
epochs=( $epoch )
j=0

for i in 50 100 200 400
do

# Training 
python pix2pix_mine2.py \
  --mode train \
  --output_dir /home/hemin/Desktop/Semi_Automatic_OSVOS/Video_1/per20_correct_aug/Trained_Model/$i \
  --max_epochs $i \
  --input_dir /home/hemin/Desktop/Semi_Automatic_OSVOS/Video_1/per20_correct_aug/Training_Set/Combine \
  --checkpoint /home/hemin/Desktop/Semi_Automatic_OSVOS/Video_1/per20_correct_aug/Trained_Model/${epochs[j]} 
let j=$j+1
done




